### ISSUE TITLE
Question about output format

### ISSUE THREAD

**Issue by SanoKyohei** [dcjones/proseg#10]
First of all, thank you for developing such a fantastic tool. We applied ProSeg to our CosMx data and observed improved performance compared to segmentation with Baysor or CellPose.

I have a few questions regarding the output, specifically the transcript-metadata.csv.gz file:

1. What is the meaning of the assignment column taking the largest number (4294967295 in our data)? These assignments are present throughout the sample and do not take the shape of cells, so we suspect they might be noise. Is this correct?

2. Approximately 0.1% of the transcriptome present in the input transcripts.csv.gz is missing in the output transcript-metadata.csv.gz. Why is this?

3. Lastly, why are the expression values for each cell in the expected-counts.csv.gz file represented as decimals instead of integers?

Thank you for your time and assistance.

**Comment by dcjones** [comment]
Hello, thanks for trying proseg!

  1. That's correct, these are unassigned transcripts. Encoding "unassigned" this way was mainly an efficiency thing, and will probably change at some point, since it's not obvious.
  2. Proseg will filter out transcripts that are very far away from any nuclei and not report these. It's generally a small proportion of the transcripts that are almost certainly noise.
  3. Expected counts are expectations in the statistical sense, estimated by taking the average over multiple samples, so they will tend to be non-integers.

**Comment by SanoKyohei** [comment]
Thank you very much!!
