### ISSUE TITLE
Downstream cell-type calling Cosmx

### ISSUE THREAD

**Issue by roanvanscheppingen** [dcjones/proseg#4]
Hi, 

With great interest I've read your preprint discussing cell segmentation. I've been working on Cosmx data and have been looking for more robust transcript assignments, since the segmentation could be improved in my opinion. Currently ~ 50% transcripts is not assigned to cells and I feel like we are losing a treasure trove of information here. 

I was wondering if you have any ideas on downstream cell-type calling. For now I've been using InSituType, which takes a reference profile curated by Nanostring. However, does your computation segmentation influence the proportion in which certain (marker) genes are detected within cell boundaries? In other words, do you know if InSituType cell-type calling is influenced negatively? Or whether cell-typing using other scRNA-seq methods (I'm working with brain tissue, so Allen Brain Atlas), would now be more beneficial? 

Best,

Roan

**Comment by dcjones** [comment]
Hi Roan,

This is a good question that I don't have a particularly good answer for. My hope is that transcript assignments are more accurate under proseg and that leads to more accurate cell type calling, but I haven't tested this with InSituType. It's definitely possible for a model to be overfit to a specific segmentation approach, causing it to fail on others.

In most the experiments I've worked on, I've annotated cell types manually by unsupervised clustering and inspecting sets of differentially expressed genes. That can be a little tedious, but has the advantage that you at least know how the decision is being made. Partially I do this because I mostly work with cancer samples, and tumor cells are all so different between samples. So I don't yet have a informed opinion on what model based tools work best.
